server:
  port: 8083

spring:
  application:
    name: test
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos 服务注册中心地址
#        namespace: 9b2f9306-1be4-4ccd-ab62-749033ea3b02  # 使用 public 命名空间可以注掉该配置
#      config:
#        server-addr: 127.0.0.1:8848  # Nacos 配置中心地址
#        file-extension: yaml          # 指定 yaml 格式的配置件
#        namespace: 9b2f9306-1be4-4ccd-ab62-749033ea3b02  # 使用 public 命名空间可以注掉该配置
    sentinel:
#      enabled: true # 自动化配置是否生效
#      eager: true   # 禁用控制台懒加载
      transport:
        dashboard: 127.0.0.1:8080  # sentinel dashboard 地址
#        port: 8721  # 默认 8719 端口，如果被占用会增加 1，可以不配，让机器自己去加
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: test-flow-rules  # 这里的配置只负责监听，与在 Nacos 生成的配置的 dataId 没有关系
            groupId: SENTINEL_GROUP  # 这里的配置只负责监听，与在 Nacos 生成的配置的 groupId 没有关系
            rule-type: flow